# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - cd ./src && go mod download
    # you may remove this if you don't need go generate
    - cd ./src && go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    dir: src
archives:
  - replacements:
      linux: Linux
      windows: Windows
      darwin: macOS
      386: x86
      amd64: x64
    format: zip
    files:
      - example_config/*
      - pi-joystick/*
      - scripts/*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
